# Generated by Django 4.2.18 on 2025-02-08 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_options_alter_product_category_and_more'),
    ]

    operations = [
    ]
